/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SenhaRouteImport } from './routes/senha'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as PoliticaRouteImport } from './routes/politica'
import { Route as MeuipRouteImport } from './routes/meuip'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as CheckRouteImport } from './routes/check'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckIndexRouteImport } from './routes/check.index'
import { Route as ClienteServicosRouteImport } from './routes/cliente_.servicos'
import { Route as ClienteMeusDadosRouteImport } from './routes/cliente_.meus-dados'
import { Route as ClienteFaturasRouteImport } from './routes/cliente_.faturas'
import { Route as ClienteDominiosRouteImport } from './routes/cliente_.dominios'
import { Route as ClienteDashboardRouteImport } from './routes/cliente_.dashboard'
import { Route as ClienteChamadosRouteImport } from './routes/cliente_.chamados'
import { Route as CheckServicosRouteImport } from './routes/check.servicos'
import { Route as CheckLoginRouteImport } from './routes/check.login'
import { Route as CheckFornecedoresRouteImport } from './routes/check.fornecedores'
import { Route as CheckFinanceiroRouteImport } from './routes/check.financeiro'
import { Route as CheckDominiosRouteImport } from './routes/check.dominios'
import { Route as CheckContasAPagarRouteImport } from './routes/check.contas-a-pagar'
import { Route as CheckClientesRouteImport } from './routes/check.clientes'
import { Route as CheckChamadosRouteImport } from './routes/check.chamados'
import { Route as PortalServicosRouteImport } from './routes/_portal.servicos'
import { Route as PortalMeusDadosRouteImport } from './routes/_portal.meus-dados'
import { Route as PortalFaturasRouteImport } from './routes/_portal.faturas'
import { Route as PortalDominiosRouteImport } from './routes/_portal.dominios'
import { Route as PortalDashboardRouteImport } from './routes/_portal.dashboard'
import { Route as PortalChamadosRouteImport } from './routes/_portal.chamados'
import { Route as ClienteFaturasIdRouteImport } from './routes/cliente_.faturas.$id'
import { Route as PortalFaturasIdRouteImport } from './routes/_portal.faturas.$id'

const SenhaRoute = SenhaRouteImport.update({
  id: '/senha',
  path: '/senha',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaRoute = PoliticaRouteImport.update({
  id: '/politica',
  path: '/politica',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuipRoute = MeuipRouteImport.update({
  id: '/meuip',
  path: '/meuip',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckRoute = CheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckIndexRoute = CheckIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckRoute,
} as any)
const ClienteServicosRoute = ClienteServicosRouteImport.update({
  id: '/cliente_/servicos',
  path: '/cliente/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteMeusDadosRoute = ClienteMeusDadosRouteImport.update({
  id: '/cliente_/meus-dados',
  path: '/cliente/meus-dados',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteFaturasRoute = ClienteFaturasRouteImport.update({
  id: '/cliente_/faturas',
  path: '/cliente/faturas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteDominiosRoute = ClienteDominiosRouteImport.update({
  id: '/cliente_/dominios',
  path: '/cliente/dominios',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteDashboardRoute = ClienteDashboardRouteImport.update({
  id: '/cliente_/dashboard',
  path: '/cliente/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteChamadosRoute = ClienteChamadosRouteImport.update({
  id: '/cliente_/chamados',
  path: '/cliente/chamados',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckServicosRoute = CheckServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => CheckRoute,
} as any)
const CheckLoginRoute = CheckLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CheckRoute,
} as any)
const CheckFornecedoresRoute = CheckFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => CheckRoute,
} as any)
const CheckFinanceiroRoute = CheckFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => CheckRoute,
} as any)
const CheckDominiosRoute = CheckDominiosRouteImport.update({
  id: '/dominios',
  path: '/dominios',
  getParentRoute: () => CheckRoute,
} as any)
const CheckContasAPagarRoute = CheckContasAPagarRouteImport.update({
  id: '/contas-a-pagar',
  path: '/contas-a-pagar',
  getParentRoute: () => CheckRoute,
} as any)
const CheckClientesRoute = CheckClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => CheckRoute,
} as any)
const CheckChamadosRoute = CheckChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => CheckRoute,
} as any)
const PortalServicosRoute = PortalServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMeusDadosRoute = PortalMeusDadosRouteImport.update({
  id: '/meus-dados',
  path: '/meus-dados',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFaturasRoute = PortalFaturasRouteImport.update({
  id: '/faturas',
  path: '/faturas',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDominiosRoute = PortalDominiosRouteImport.update({
  id: '/dominios',
  path: '/dominios',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalChamadosRoute = PortalChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => PortalRoute,
} as any)
const ClienteFaturasIdRoute = ClienteFaturasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClienteFaturasRoute,
} as any)
const PortalFaturasIdRoute = PortalFaturasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalFaturasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check': typeof CheckRouteWithChildren
  '/cliente': typeof ClienteRoute
  '/contato': typeof ContatoRoute
  '/download': typeof DownloadRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/meuip': typeof MeuipRoute
  '/politica': typeof PoliticaRoute
  '/quem-somos': typeof QuemSomosRoute
  '/senha': typeof SenhaRoute
  '/chamados': typeof PortalChamadosRoute
  '/dashboard': typeof PortalDashboardRoute
  '/dominios': typeof PortalDominiosRoute
  '/faturas': typeof PortalFaturasRouteWithChildren
  '/meus-dados': typeof PortalMeusDadosRoute
  '/servicos': typeof PortalServicosRoute
  '/check/chamados': typeof CheckChamadosRoute
  '/check/clientes': typeof CheckClientesRoute
  '/check/contas-a-pagar': typeof CheckContasAPagarRoute
  '/check/dominios': typeof CheckDominiosRoute
  '/check/financeiro': typeof CheckFinanceiroRoute
  '/check/fornecedores': typeof CheckFornecedoresRoute
  '/check/login': typeof CheckLoginRoute
  '/check/servicos': typeof CheckServicosRoute
  '/cliente/chamados': typeof ClienteChamadosRoute
  '/cliente/dashboard': typeof ClienteDashboardRoute
  '/cliente/dominios': typeof ClienteDominiosRoute
  '/cliente/faturas': typeof ClienteFaturasRouteWithChildren
  '/cliente/meus-dados': typeof ClienteMeusDadosRoute
  '/cliente/servicos': typeof ClienteServicosRoute
  '/check/': typeof CheckIndexRoute
  '/faturas/$id': typeof PortalFaturasIdRoute
  '/cliente/faturas/$id': typeof ClienteFaturasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRoute
  '/contato': typeof ContatoRoute
  '/download': typeof DownloadRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/meuip': typeof MeuipRoute
  '/politica': typeof PoliticaRoute
  '/quem-somos': typeof QuemSomosRoute
  '/senha': typeof SenhaRoute
  '/chamados': typeof PortalChamadosRoute
  '/dashboard': typeof PortalDashboardRoute
  '/dominios': typeof PortalDominiosRoute
  '/faturas': typeof PortalFaturasRouteWithChildren
  '/meus-dados': typeof PortalMeusDadosRoute
  '/servicos': typeof PortalServicosRoute
  '/check/chamados': typeof CheckChamadosRoute
  '/check/clientes': typeof CheckClientesRoute
  '/check/contas-a-pagar': typeof CheckContasAPagarRoute
  '/check/dominios': typeof CheckDominiosRoute
  '/check/financeiro': typeof CheckFinanceiroRoute
  '/check/fornecedores': typeof CheckFornecedoresRoute
  '/check/login': typeof CheckLoginRoute
  '/check/servicos': typeof CheckServicosRoute
  '/cliente/chamados': typeof ClienteChamadosRoute
  '/cliente/dashboard': typeof ClienteDashboardRoute
  '/cliente/dominios': typeof ClienteDominiosRoute
  '/cliente/faturas': typeof ClienteFaturasRouteWithChildren
  '/cliente/meus-dados': typeof ClienteMeusDadosRoute
  '/cliente/servicos': typeof ClienteServicosRoute
  '/check': typeof CheckIndexRoute
  '/faturas/$id': typeof PortalFaturasIdRoute
  '/cliente/faturas/$id': typeof ClienteFaturasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_portal': typeof PortalRouteWithChildren
  '/check': typeof CheckRouteWithChildren
  '/cliente': typeof ClienteRoute
  '/contato': typeof ContatoRoute
  '/download': typeof DownloadRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/meuip': typeof MeuipRoute
  '/politica': typeof PoliticaRoute
  '/quem-somos': typeof QuemSomosRoute
  '/senha': typeof SenhaRoute
  '/_portal/chamados': typeof PortalChamadosRoute
  '/_portal/dashboard': typeof PortalDashboardRoute
  '/_portal/dominios': typeof PortalDominiosRoute
  '/_portal/faturas': typeof PortalFaturasRouteWithChildren
  '/_portal/meus-dados': typeof PortalMeusDadosRoute
  '/_portal/servicos': typeof PortalServicosRoute
  '/check/chamados': typeof CheckChamadosRoute
  '/check/clientes': typeof CheckClientesRoute
  '/check/contas-a-pagar': typeof CheckContasAPagarRoute
  '/check/dominios': typeof CheckDominiosRoute
  '/check/financeiro': typeof CheckFinanceiroRoute
  '/check/fornecedores': typeof CheckFornecedoresRoute
  '/check/login': typeof CheckLoginRoute
  '/check/servicos': typeof CheckServicosRoute
  '/cliente_/chamados': typeof ClienteChamadosRoute
  '/cliente_/dashboard': typeof ClienteDashboardRoute
  '/cliente_/dominios': typeof ClienteDominiosRoute
  '/cliente_/faturas': typeof ClienteFaturasRouteWithChildren
  '/cliente_/meus-dados': typeof ClienteMeusDadosRoute
  '/cliente_/servicos': typeof ClienteServicosRoute
  '/check/': typeof CheckIndexRoute
  '/_portal/faturas/$id': typeof PortalFaturasIdRoute
  '/cliente_/faturas/$id': typeof ClienteFaturasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check'
    | '/cliente'
    | '/contato'
    | '/download'
    | '/esqueci-senha'
    | '/login'
    | '/meuip'
    | '/politica'
    | '/quem-somos'
    | '/senha'
    | '/chamados'
    | '/dashboard'
    | '/dominios'
    | '/faturas'
    | '/meus-dados'
    | '/servicos'
    | '/check/chamados'
    | '/check/clientes'
    | '/check/contas-a-pagar'
    | '/check/dominios'
    | '/check/financeiro'
    | '/check/fornecedores'
    | '/check/login'
    | '/check/servicos'
    | '/cliente/chamados'
    | '/cliente/dashboard'
    | '/cliente/dominios'
    | '/cliente/faturas'
    | '/cliente/meus-dados'
    | '/cliente/servicos'
    | '/check/'
    | '/faturas/$id'
    | '/cliente/faturas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cliente'
    | '/contato'
    | '/download'
    | '/esqueci-senha'
    | '/login'
    | '/meuip'
    | '/politica'
    | '/quem-somos'
    | '/senha'
    | '/chamados'
    | '/dashboard'
    | '/dominios'
    | '/faturas'
    | '/meus-dados'
    | '/servicos'
    | '/check/chamados'
    | '/check/clientes'
    | '/check/contas-a-pagar'
    | '/check/dominios'
    | '/check/financeiro'
    | '/check/fornecedores'
    | '/check/login'
    | '/check/servicos'
    | '/cliente/chamados'
    | '/cliente/dashboard'
    | '/cliente/dominios'
    | '/cliente/faturas'
    | '/cliente/meus-dados'
    | '/cliente/servicos'
    | '/check'
    | '/faturas/$id'
    | '/cliente/faturas/$id'
  id:
    | '__root__'
    | '/'
    | '/_portal'
    | '/check'
    | '/cliente'
    | '/contato'
    | '/download'
    | '/esqueci-senha'
    | '/login'
    | '/meuip'
    | '/politica'
    | '/quem-somos'
    | '/senha'
    | '/_portal/chamados'
    | '/_portal/dashboard'
    | '/_portal/dominios'
    | '/_portal/faturas'
    | '/_portal/meus-dados'
    | '/_portal/servicos'
    | '/check/chamados'
    | '/check/clientes'
    | '/check/contas-a-pagar'
    | '/check/dominios'
    | '/check/financeiro'
    | '/check/fornecedores'
    | '/check/login'
    | '/check/servicos'
    | '/cliente_/chamados'
    | '/cliente_/dashboard'
    | '/cliente_/dominios'
    | '/cliente_/faturas'
    | '/cliente_/meus-dados'
    | '/cliente_/servicos'
    | '/check/'
    | '/_portal/faturas/$id'
    | '/cliente_/faturas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
  CheckRoute: typeof CheckRouteWithChildren
  ClienteRoute: typeof ClienteRoute
  ContatoRoute: typeof ContatoRoute
  DownloadRoute: typeof DownloadRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  MeuipRoute: typeof MeuipRoute
  PoliticaRoute: typeof PoliticaRoute
  QuemSomosRoute: typeof QuemSomosRoute
  SenhaRoute: typeof SenhaRoute
  ClienteChamadosRoute: typeof ClienteChamadosRoute
  ClienteDashboardRoute: typeof ClienteDashboardRoute
  ClienteDominiosRoute: typeof ClienteDominiosRoute
  ClienteFaturasRoute: typeof ClienteFaturasRouteWithChildren
  ClienteMeusDadosRoute: typeof ClienteMeusDadosRoute
  ClienteServicosRoute: typeof ClienteServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/senha': {
      id: '/senha'
      path: '/senha'
      fullPath: '/senha'
      preLoaderRoute: typeof SenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica': {
      id: '/politica'
      path: '/politica'
      fullPath: '/politica'
      preLoaderRoute: typeof PoliticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meuip': {
      id: '/meuip'
      path: '/meuip'
      fullPath: '/meuip'
      preLoaderRoute: typeof MeuipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check': {
      id: '/check'
      path: '/check'
      fullPath: '/check'
      preLoaderRoute: typeof CheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check/': {
      id: '/check/'
      path: '/'
      fullPath: '/check/'
      preLoaderRoute: typeof CheckIndexRouteImport
      parentRoute: typeof CheckRoute
    }
    '/cliente_/servicos': {
      id: '/cliente_/servicos'
      path: '/cliente/servicos'
      fullPath: '/cliente/servicos'
      preLoaderRoute: typeof ClienteServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente_/meus-dados': {
      id: '/cliente_/meus-dados'
      path: '/cliente/meus-dados'
      fullPath: '/cliente/meus-dados'
      preLoaderRoute: typeof ClienteMeusDadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente_/faturas': {
      id: '/cliente_/faturas'
      path: '/cliente/faturas'
      fullPath: '/cliente/faturas'
      preLoaderRoute: typeof ClienteFaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente_/dominios': {
      id: '/cliente_/dominios'
      path: '/cliente/dominios'
      fullPath: '/cliente/dominios'
      preLoaderRoute: typeof ClienteDominiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente_/dashboard': {
      id: '/cliente_/dashboard'
      path: '/cliente/dashboard'
      fullPath: '/cliente/dashboard'
      preLoaderRoute: typeof ClienteDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente_/chamados': {
      id: '/cliente_/chamados'
      path: '/cliente/chamados'
      fullPath: '/cliente/chamados'
      preLoaderRoute: typeof ClienteChamadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check/servicos': {
      id: '/check/servicos'
      path: '/servicos'
      fullPath: '/check/servicos'
      preLoaderRoute: typeof CheckServicosRouteImport
      parentRoute: typeof CheckRoute
    }
    '/check/login': {
      id: '/check/login'
      path: '/login'
      fullPath: '/check/login'
      preLoaderRoute: typeof CheckLoginRouteImport
      parentRoute: typeof CheckRoute
    }
    '/check/fornecedores': {
      id: '/check/fornecedores'
      path: '/fornecedores'
      fullPath: '/check/fornecedores'
      preLoaderRoute: typeof CheckFornecedoresRouteImport
      parentRoute: typeof CheckRoute
    }
    '/check/financeiro': {
      id: '/check/financeiro'
      path: '/financeiro'
      fullPath: '/check/financeiro'
      preLoaderRoute: typeof CheckFinanceiroRouteImport
      parentRoute: typeof CheckRoute
    }
    '/check/dominios': {
      id: '/check/dominios'
      path: '/dominios'
      fullPath: '/check/dominios'
      preLoaderRoute: typeof CheckDominiosRouteImport
      parentRoute: typeof CheckRoute
    }
    '/check/contas-a-pagar': {
      id: '/check/contas-a-pagar'
      path: '/contas-a-pagar'
      fullPath: '/check/contas-a-pagar'
      preLoaderRoute: typeof CheckContasAPagarRouteImport
      parentRoute: typeof CheckRoute
    }
    '/check/clientes': {
      id: '/check/clientes'
      path: '/clientes'
      fullPath: '/check/clientes'
      preLoaderRoute: typeof CheckClientesRouteImport
      parentRoute: typeof CheckRoute
    }
    '/check/chamados': {
      id: '/check/chamados'
      path: '/chamados'
      fullPath: '/check/chamados'
      preLoaderRoute: typeof CheckChamadosRouteImport
      parentRoute: typeof CheckRoute
    }
    '/_portal/servicos': {
      id: '/_portal/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof PortalServicosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/meus-dados': {
      id: '/_portal/meus-dados'
      path: '/meus-dados'
      fullPath: '/meus-dados'
      preLoaderRoute: typeof PortalMeusDadosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/faturas': {
      id: '/_portal/faturas'
      path: '/faturas'
      fullPath: '/faturas'
      preLoaderRoute: typeof PortalFaturasRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/dominios': {
      id: '/_portal/dominios'
      path: '/dominios'
      fullPath: '/dominios'
      preLoaderRoute: typeof PortalDominiosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/dashboard': {
      id: '/_portal/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/chamados': {
      id: '/_portal/chamados'
      path: '/chamados'
      fullPath: '/chamados'
      preLoaderRoute: typeof PortalChamadosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/cliente_/faturas/$id': {
      id: '/cliente_/faturas/$id'
      path: '/$id'
      fullPath: '/cliente/faturas/$id'
      preLoaderRoute: typeof ClienteFaturasIdRouteImport
      parentRoute: typeof ClienteFaturasRoute
    }
    '/_portal/faturas/$id': {
      id: '/_portal/faturas/$id'
      path: '/$id'
      fullPath: '/faturas/$id'
      preLoaderRoute: typeof PortalFaturasIdRouteImport
      parentRoute: typeof PortalFaturasRoute
    }
  }
}

interface PortalFaturasRouteChildren {
  PortalFaturasIdRoute: typeof PortalFaturasIdRoute
}

const PortalFaturasRouteChildren: PortalFaturasRouteChildren = {
  PortalFaturasIdRoute: PortalFaturasIdRoute,
}

const PortalFaturasRouteWithChildren = PortalFaturasRoute._addFileChildren(
  PortalFaturasRouteChildren,
)

interface PortalRouteChildren {
  PortalChamadosRoute: typeof PortalChamadosRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalDominiosRoute: typeof PortalDominiosRoute
  PortalFaturasRoute: typeof PortalFaturasRouteWithChildren
  PortalMeusDadosRoute: typeof PortalMeusDadosRoute
  PortalServicosRoute: typeof PortalServicosRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalChamadosRoute: PortalChamadosRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalDominiosRoute: PortalDominiosRoute,
  PortalFaturasRoute: PortalFaturasRouteWithChildren,
  PortalMeusDadosRoute: PortalMeusDadosRoute,
  PortalServicosRoute: PortalServicosRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface CheckRouteChildren {
  CheckChamadosRoute: typeof CheckChamadosRoute
  CheckClientesRoute: typeof CheckClientesRoute
  CheckContasAPagarRoute: typeof CheckContasAPagarRoute
  CheckDominiosRoute: typeof CheckDominiosRoute
  CheckFinanceiroRoute: typeof CheckFinanceiroRoute
  CheckFornecedoresRoute: typeof CheckFornecedoresRoute
  CheckLoginRoute: typeof CheckLoginRoute
  CheckServicosRoute: typeof CheckServicosRoute
  CheckIndexRoute: typeof CheckIndexRoute
}

const CheckRouteChildren: CheckRouteChildren = {
  CheckChamadosRoute: CheckChamadosRoute,
  CheckClientesRoute: CheckClientesRoute,
  CheckContasAPagarRoute: CheckContasAPagarRoute,
  CheckDominiosRoute: CheckDominiosRoute,
  CheckFinanceiroRoute: CheckFinanceiroRoute,
  CheckFornecedoresRoute: CheckFornecedoresRoute,
  CheckLoginRoute: CheckLoginRoute,
  CheckServicosRoute: CheckServicosRoute,
  CheckIndexRoute: CheckIndexRoute,
}

const CheckRouteWithChildren = CheckRoute._addFileChildren(CheckRouteChildren)

interface ClienteFaturasRouteChildren {
  ClienteFaturasIdRoute: typeof ClienteFaturasIdRoute
}

const ClienteFaturasRouteChildren: ClienteFaturasRouteChildren = {
  ClienteFaturasIdRoute: ClienteFaturasIdRoute,
}

const ClienteFaturasRouteWithChildren = ClienteFaturasRoute._addFileChildren(
  ClienteFaturasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
  CheckRoute: CheckRouteWithChildren,
  ClienteRoute: ClienteRoute,
  ContatoRoute: ContatoRoute,
  DownloadRoute: DownloadRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  MeuipRoute: MeuipRoute,
  PoliticaRoute: PoliticaRoute,
  QuemSomosRoute: QuemSomosRoute,
  SenhaRoute: SenhaRoute,
  ClienteChamadosRoute: ClienteChamadosRoute,
  ClienteDashboardRoute: ClienteDashboardRoute,
  ClienteDominiosRoute: ClienteDominiosRoute,
  ClienteFaturasRoute: ClienteFaturasRouteWithChildren,
  ClienteMeusDadosRoute: ClienteMeusDadosRoute,
  ClienteServicosRoute: ClienteServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
